# render.yaml

services:
  - type: web
    name: bank-churn-predictor
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.18
    plan: free
    autoDeploy: true
